# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-08 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adult_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('workclass', models.CharField(max_length=100)),
                ('fnlwgt', models.BigIntegerField()),
                ('education', models.CharField(max_length=100)),
                ('education_num', models.BigIntegerField()),
                ('marital_status', models.TextField()),
                ('occupation', models.CharField(max_length=100)),
                ('relationship', models.TextField()),
                ('race', models.TextField()),
                ('sex', models.TextField()),
                ('capital_gain', models.BigIntegerField()),
                ('capital_loss', models.BigIntegerField()),
                ('hours_per_week', models.BigIntegerField()),
                ('native_country', models.CharField(max_length=100)),
                ('country_value', models.TextField()),
            ],
            options={
                'db_table': 'adult_data',
            },
        ),
    ]
